CREATE DATABASE restaurant_database;

USE restaurant_database;

CREATE TABLE MEALS (
    meal_id INT PRIMARY KEY,
    meal_name VARCHAR(255),
    price DECIMAL(10, 2),
    calories INT
);


CREATE TABLE INGREDIENT (
    ingredient_id INT PRIMARY KEY,
    ingredient_name VARCHAR(255),
    is_vegan BOOLEAN,
    has_lactose BOOLEAN
);

CREATE TABLE CHEAP_MEALS AS
SELECT *
FROM MEALS
WHERE price < 15;

INSERT INTO VEGAN_INGREDIENT
SELECT *
FROM INGREDIENT
WHERE is_vegan = TRUE;

CREATE VIEW EXPENSIVE_MEAL AS
SELECT *
FROM MEALS
WHERE price > 15;

CREATE VIEW LACTOSE_FREE_INGREDIENT AS
SELECT *
FROM INGREDIENT
WHERE has_lactose = FALSE;

CREATE TABLE HIGH_CALORIE_MEAL AS
SELECT *
FROM MEALS
WHERE calories > 650;
